# Generated by Django 4.2.5 on 2023-10-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
